apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-redis
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp-redis
  template:
    metadata:
      labels:
        app: myapp-redis
    spec:
      containers:
      - name: myapp-redis
        image: redis
        # resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
        - containerPort: 6379 #default port of redis
        volumeMounts:
        - name: redis-hostpath-vol
          mountPath: /redis-host-data
      volumes:
      - name: redis-hostpath-vol
        hostPath:
          path: /tmp/redis-host-data
