apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole #cluster level role assignment access , generally devops eng will get this access
metadata:
  name: pod-log-reader-clusterrole #user should mention in role binding
rules:
- apiGroups:
  - ""
  resources:
    - pods
    - pods/log
    - deployments
  verbs: ["get","list"] #api methods

  
  