apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx
  labels:
    app: myapp-nginx
  namespace: dev-ns-team
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-nginx
  template:
    metadata:
      labels:
        app: myapp-nginx
    spec:
      containers:
      - name: myapp-nginx
        image: nginx
        resources:
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-nginx-service
  namespace: dev-ns-team
spec:
  selector:
    app: myapp-nginx
  ports:
  - port: 80

