apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-log-reader-binding
  namespace: dev-ns-team
subjects:
- kind: User
  name: 86nsarada@gmail.com
  apiGroup: rbac.authorization.k8s.io
# - kind: Group 
#   name: 86nsarada@gmail.com
#   apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: Role
  name: pod-log-reader
  apiGroup: rbac.authorization.k8s.io