apiVersion: rbac.authorization.k8s.io/v1
kind: Role #namespace level role assignment access, generally other teams like dev, test get role access not cluster level access
metadata:
  name: pod-log-reader #user should mention in role binding
  namespace: dev-ns-team
rules:
- apiGroups:
  - ""
  resources:
    - pods
    - pods/log
  verbs: ["get","list"] #api methods

  
  