---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: myapp
#   labels:
#     name: myapp
#   spec:
#     containers:
#       - name: myapp
#         image: nginx
#         resources:
#           limits:
#             memory: 128Mi
#             cpu: 500m
#         ports:
#           - containerPort: 80
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
      - containerPort: 80
