---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-node-deploy
  labels:
    app: httpd-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd-deploy
  template:
    metadata:
      labels:
        app: httpd-deploy
    spec:
      containers:
      - name: httpd-node-deploy
        image: httpd
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-node-service
  labels:
    app: httpd-deploy
spec:
  selector:
    app: httpd-deploy
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
