apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev-config
spec:
  selector:
    matchLabels:
      app: nginx-dev-config
  template:
    metadata:
      labels:
        app: nginx-dev-config
    spec:
      containers:
      - name: nginx-dev-config
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-nginx-volume
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config-nginx-volume
        configMap:
          name: nginx-config-dev
      resources:
        
