apiVersion: v1
kind: LimitRange
metadata:
  name: test-team-limit-range
  namespace: test-team
spec:
  limits: 
  - type: Pod 
    min: #requests
      cpu: "100m"
      memory: "200Mi" # 1Gi = 1000 Mi
    max:
      cpu: "200m"
      memory: "250Mi"